#!/bin/bash

EXTRA_ARGS=
TRILINOS_SRC_DIR=/Users/fnrizzi/tpl/trilinos/Trilinos
PFX=/Users/fnrizzi/tpl/trilinos/install_gcc640_serial
CC=/opt/local/bin/gcc-mp-6
CXX=/opt/local/bin/g++-mp-6

cmake \
    -D CMAKE_BUILD_TYPE:STRING=DEBUG \
    -D CMAKE_INSTALL_PREFIX:PATH=${PFX} \
    -D BUILD_SHARED_LIBS:BOOL=ON \
    \
    -D TPL_ENABLE_MPI:BOOL=OFF \
    -D CMAKE_C_COMPILER:FILEPATH=${CC} \
    -D CMAKE_CXX_COMPILER:FILEPATH=${CXX} \
    \
    -D PYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7 \
    -D Trilinos_ENABLE_EXPORT_MAKEFILES:BOOL=OFF \
    -D TPL_ENABLE_BoostLib:BOOL=OFF \
    -D Trilinos_ENABLE_Fortran:BOOL=OFF \
    -D Trilinos_ENABLE_TESTS:BOOL=OFF \
    -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
    -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
    \
    -D Trilinos_ENABLE_OpenMP:BOOL=ON \
    -D KOKKOS_ENABLE_SERIAL:BOOL=OFF \
    -D KOKKOS_ENABLE_THREADS:BOOL=OFF \
    -D KOKKOS_ENABLE_OPENMP:BOOL=ON \
    \
    -D Trilinos_ENABLE_Teuchos:BOOL=ON \
    -D Trilinos_ENABLE_Epetra:BOOL=ON \
    -D Trilinos_ENABLE_Tpetra:BOOL=ON \
    -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
    \
    -D Trilinos_ENABLE_AztecOO:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack:BOOL=ON \
    -D Trilinos_ENABLE_Ifpack2:BOOL=ON \
    -D Trilinos_ENABLE_ML:BOOL=ON \
    -D Trilinos_ENABLE_Amesos2:BOOL=ON \
    \
    -D Trilinos_ENABLE_ROL:BOOL=ON \
    -D Trilinos_ENABLE_NOX:BOOL=ON \
    -D NOX_ENABLE_LOCA:BOOL=ON \
    \
    -D Trilinos_ENABLE_Anasazi:BOOL=ON \
    -D Trilinos_ENABLE_MueLu:BOOL=ON \
    \
    -D Trilinos_ENABLE_PyTrilinos:BOOL=OFF \
    -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
    ${TRILINOS_SRC_DIR} \
    $EXTRA_ARGS
